# Generated by Django 4.2.1 on 2023-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="audio_files/")),
                ("transcription_text", models.TextField()),
                ("transcribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
